2025-06-07T15:03:39.717666+0000 INFO Route '/retrain' called for retraining with data_path=data/df_modifie.csv, from_existing_model=False
2025-06-07T15:03:39.726473+0000 INFO Données chargées pour réentraînement: shape=(2000, 13), colonnes=['nom', 'prenom', 'age', 'taille', 'poids', 'sexe', 'sport_licence', 'niveau_etude', 'region', 'smoker', 'nationalité_francaise', 'revenu_estime_mois', 'montant_pret']
2025-06-07T15:03:39.726780+0000 INFO Starting training iteration 0 of 3 (from_existing_model=False)
2025-06-07T15:03:39.761169+0000 INFO No previous model_id, creating new model.
2025-06-07T15:03:47.954369+0000 INFO Model performances: {'MSE': 172693088.0, 'MAE': 13007.3974609375, 'R²': 0.6067548990249634}
2025-06-07T15:07:54.828920+0000 ERROR Erreur lors du réentraînement: API request to http://localhost:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7302a5549fc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-07T15:08:13.842781+0000 INFO Route '/retrain' called for retraining with data_path=data/df_modifie.csv, from_existing_model=True
2025-06-07T15:08:13.849754+0000 INFO Données chargées pour réentraînement: shape=(2000, 13), colonnes=['nom', 'prenom', 'age', 'taille', 'poids', 'sexe', 'sport_licence', 'niveau_etude', 'region', 'smoker', 'nationalité_francaise', 'revenu_estime_mois', 'montant_pret']
2025-06-07T15:08:13.850064+0000 INFO Starting training iteration 0 of 3 (from_existing_model=True)
2025-06-07T15:08:13.871860+0000 INFO Loading model from previous model_id: 60ca87cde38a42dab673c4c6491ba076
2025-06-07T15:09:17.482650+0000 INFO Route '/predict' called with data: [30, 170.0, 70.0, 2500.0, 'M', 'Oui', 'Aucun', 'Auvergne-Rhône-Alpes', 'Oui', 'Oui']
2025-06-07T15:12:20.208092+0000 ERROR Erreur lors du réentraînement: API request to http://localhost:5000/api/2.0/mlflow/runs/get failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/get?run_uuid=60ca87cde38a42dab673c4c6491ba076&run_id=60ca87cde38a42dab673c4c6491ba076 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7302a554b670>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-07T15:13:23.744959+0000 ERROR Erreur lors de la prédiction: API request to http://localhost:5000/api/2.0/mlflow/runs/get failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/get?run_uuid=60ca87cde38a42dab673c4c6491ba076&run_id=60ca87cde38a42dab673c4c6491ba076 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b8b3fce5a80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-07T15:26:29.471665+0000 INFO Route '/current_model' called by 172.18.0.1
2025-06-07T15:26:56.085670+0000 INFO Route '/retrain' called for retraining with data_path=data/df_new.csv, from_existing_model=False
2025-06-07T15:26:56.103644+0000 INFO Données chargées pour réentraînement: shape=(2000, 13), colonnes=['nom', 'prenom', 'age', 'taille', 'poids', 'sexe', 'sport_licence', 'niveau_etude', 'region', 'smoker', 'nationalité_francaise', 'revenu_estime_mois', 'montant_pret']
2025-06-07T15:26:56.103938+0000 INFO Starting training iteration 0 of 3 (from_existing_model=False)
2025-06-07T15:26:56.138684+0000 INFO No previous model_id, creating new model.
2025-06-07T15:27:04.170988+0000 INFO Model performances: {'MSE': 16929087.44312835, 'MAE': 2877.6568122076524, 'R²': 0.8436144466189229}
2025-06-07T15:31:11.099954+0000 ERROR Erreur lors du réentraînement: API request to http://localhost:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x711afc6269e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-07T15:31:11.512145+0000 INFO Route '/retrain' called for retraining with data_path=df_new.csv, from_existing_model=False
2025-06-07T15:31:11.512992+0000 ERROR Erreur lors du réentraînement: [Errno 2] No such file or directory: 'df_new.csv'
2025-06-07T15:31:31.090069+0000 INFO Route '/retrain' called for retraining with data_path=./data/df_new.csv, from_existing_model=False
2025-06-07T15:31:31.098160+0000 INFO Données chargées pour réentraînement: shape=(2000, 13), colonnes=['nom', 'prenom', 'age', 'taille', 'poids', 'sexe', 'sport_licence', 'niveau_etude', 'region', 'smoker', 'nationalité_francaise', 'revenu_estime_mois', 'montant_pret']
2025-06-07T15:31:31.098494+0000 INFO Starting training iteration 0 of 3 (from_existing_model=False)
2025-06-07T15:31:31.118012+0000 INFO No previous model_id, creating new model.
2025-06-07T15:31:38.635675+0000 INFO Model performances: {'MSE': 15621119.169517599, 'MAE': 2711.4383211437043, 'R²': 0.8556970436851066}
2025-06-07T15:34:30.413845+0000 INFO Route '/predict' called with data: [30, 170.0, 70.0, 2500.0, 'M', 'Oui', 'Aucun', 'Auvergne-Rhône-Alpes', 'Oui', 'Oui']
2025-06-07T15:34:30.417149+0000 ERROR Erreur lors de la prédiction: 404: Aucun run_id trouvé. Veuillez entraîner un modèle d'abord.
2025-06-07T15:35:44.459976+0000 ERROR Erreur lors du réentraînement: API request to http://localhost:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x711afc36a560>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-07T15:35:44.463307+0000 INFO Route '/retrain' called for retraining with data_path=./data/df_new.csv, from_existing_model=False
2025-06-07T15:35:44.476551+0000 INFO Données chargées pour réentraînement: shape=(2000, 13), colonnes=['nom', 'prenom', 'age', 'taille', 'poids', 'sexe', 'sport_licence', 'niveau_etude', 'region', 'smoker', 'nationalité_francaise', 'revenu_estime_mois', 'montant_pret']
2025-06-07T15:35:44.477098+0000 INFO Starting training iteration 0 of 3 (from_existing_model=False)
2025-06-07T15:35:44.519877+0000 INFO No previous model_id, creating new model.
2025-06-07T15:35:51.671091+0000 INFO Model performances: {'MSE': 15498890.08549305, 'MAE': 2700.676783844548, 'R²': 0.8568261572896441}
2025-06-07T15:39:58.681498+0000 ERROR Erreur lors du réentraînement: API request to http://localhost:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x711addf3e4a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-07T15:39:58.684262+0000 INFO Route '/retrain' called for retraining with data_path=data/df_new.csv, from_existing_model=False
2025-06-07T15:39:58.704335+0000 INFO Données chargées pour réentraînement: shape=(2000, 13), colonnes=['nom', 'prenom', 'age', 'taille', 'poids', 'sexe', 'sport_licence', 'niveau_etude', 'region', 'smoker', 'nationalité_francaise', 'revenu_estime_mois', 'montant_pret']
2025-06-07T15:39:58.704900+0000 INFO Starting training iteration 0 of 3 (from_existing_model=False)
2025-06-07T15:39:58.740733+0000 INFO No previous model_id, creating new model.
2025-06-07T15:40:07.677319+0000 INFO Model performances: {'MSE': 17196578.947233237, 'MAE': 2896.787637944473, 'R²': 0.8411434447391872}
2025-06-07T15:44:14.389983+0000 ERROR Erreur lors du réentraînement: API request to http://localhost:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x711b24251840>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-07T16:18:44.022715+0000 INFO Route '/retrain' called for retraining with data_path=data/df_new.csv, from_existing_model=False
2025-06-07T16:18:44.031995+0000 INFO Données chargées pour réentraînement: shape=(2000, 13), colonnes=['nom', 'prenom', 'age', 'taille', 'poids', 'sexe', 'sport_licence', 'niveau_etude', 'region', 'smoker', 'nationalité_francaise', 'revenu_estime_mois', 'montant_pret']
2025-06-07T16:18:44.032314+0000 INFO Starting training iteration 0 of 3 (from_existing_model=False)
2025-06-07T16:18:44.061575+0000 INFO No previous model_id, creating new model.
2025-06-07T16:18:52.137850+0000 INFO Model performances: {'MSE': 16501568.078882057, 'MAE': 2885.0196384076007, 'R²': 0.8475637352373074}
2025-06-07T16:22:59.856164+0000 ERROR Erreur lors du réentraînement: API request to http://localhost:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7cbb78ecada0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-07T16:47:09.492289+0000 INFO Route '/health' called by 172.18.0.1
2025-06-07T16:47:26.517033+0000 INFO Route '/current_model' called by 172.18.0.1
2025-06-07T16:47:39.670437+0000 INFO Route '/retrain' called for retraining with data_path=string, from_existing_model=True
2025-06-07T16:47:39.672047+0000 ERROR Erreur lors du réentraînement: [Errno 2] No such file or directory: 'string'
2025-06-07T16:48:35.535673+0000 INFO Route '/retrain' called for retraining with data_path=./data/df_new.csv, from_existing_model=False
2025-06-07T16:48:35.544589+0000 INFO Données chargées pour réentraînement: shape=(2000, 13), colonnes=['nom', 'prenom', 'age', 'taille', 'poids', 'sexe', 'sport_licence', 'niveau_etude', 'region', 'smoker', 'nationalité_francaise', 'revenu_estime_mois', 'montant_pret']
2025-06-07T16:48:35.545035+0000 INFO Starting training iteration 0 of 3 (from_existing_model=False)
2025-06-07T16:48:35.566003+0000 INFO No previous model_id, creating new model.
2025-06-07T16:48:42.847047+0000 INFO Model performances: {'MSE': 15408442.573178096, 'MAE': 2688.6466271209965, 'R²': 0.8576616827905215}
2025-06-07T16:52:49.535540+0000 ERROR Erreur lors du réentraînement: API request to http://localhost:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7cbb78c05b10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-08T06:58:40.118810+0000 INFO Route '/health' called by 172.18.0.1
2025-06-08T07:01:42.276451+0000 INFO Route '/retrain' called for retraining with data_path=data/df_new.csv, from_existing_model=False
2025-06-08T07:01:42.293097+0000 INFO Données chargées pour réentraînement: shape=(2000, 13), colonnes=['nom', 'prenom', 'age', 'taille', 'poids', 'sexe', 'sport_licence', 'niveau_etude', 'region', 'smoker', 'nationalité_francaise', 'revenu_estime_mois', 'montant_pret']
2025-06-08T07:01:42.293467+0000 INFO Starting training iteration 0 of 3 (from_existing_model=False)
2025-06-08T07:01:42.329917+0000 INFO No previous model_id, creating new model.
2025-06-08T07:01:49.585212+0000 INFO Model performances: {'MSE': 17554233.808725044, 'MAE': 2932.7504384591516, 'R²': 0.837839542291892}
2025-06-08T07:01:59.141821+0000 INFO Run 1 terminé, run_id=c685e1fa84fc4e6481e9d064326e47f6
2025-06-08T07:01:59.156818+0000 INFO Starting training iteration 1 of 3 (from_existing_model=False)
2025-06-08T07:01:59.175161+0000 INFO Loading model from previous model_id: c685e1fa84fc4e6481e9d064326e47f6
2025-06-08T07:02:07.135448+0000 INFO Model performances: {'MSE': 13495073.020743584, 'MAE': 2403.6706294908627, 'R²': 0.8753367853195376}
2025-06-08T07:02:12.993232+0000 INFO Run 2 terminé, run_id=ebaa8a12c48a4961af59d212f8d5f520
2025-06-08T07:02:13.007250+0000 INFO Starting training iteration 2 of 3 (from_existing_model=False)
2025-06-08T07:02:13.025405+0000 INFO Loading model from previous model_id: ebaa8a12c48a4961af59d212f8d5f520
2025-06-08T07:02:19.787414+0000 INFO Model performances: {'MSE': 13503135.880122967, 'MAE': 2391.356168394, 'R²': 0.875262303175706}
2025-06-08T07:02:25.674654+0000 INFO Run 3 terminé, run_id=e68a2055f1a84f30aaff68726060634f
2025-06-08T07:02:25.690974+0000 INFO Nouveau modèle de prédiction mis à jour avec run_id: e68a2055f1a84f30aaff68726060634f (sauvegardé dans models/current_model.json)
2025-06-08T07:06:33.619685+0000 INFO Route '/predict' called with data: [30, 170.0, 70.0, 2500.0, 'M', 'Oui', 'Aucun', 'Auvergne-Rhône-Alpes', 'Oui', 'Oui']
2025-06-08T07:06:33.688579+0000 INFO Model loaded from MLflow run ID: e68a2055f1a84f30aaff68726060634f
2025-06-08T07:06:33.790651+0000 INFO Prediction made: [3182.0725], prediction value: 3182.072509765625
2025-06-08T07:06:52.006191+0000 INFO Route '/predict' called with data: [30, 137.0, 96.0, 11100.0, 'M', 'Oui', 'Aucun', 'Auvergne-Rhône-Alpes', 'Oui', 'Oui']
2025-06-08T07:06:52.089430+0000 INFO Model loaded from MLflow run ID: e68a2055f1a84f30aaff68726060634f
2025-06-08T07:06:52.168607+0000 INFO Prediction made: [38043.96], prediction value: 38043.9609375
2025-06-08T07:07:33.355974+0000 INFO Route '/retrain' called for retraining with data_path=data/df_modifie.csv, from_existing_model=False
2025-06-08T07:07:33.366430+0000 INFO Données chargées pour réentraînement: shape=(2000, 13), colonnes=['nom', 'prenom', 'age', 'taille', 'poids', 'sexe', 'sport_licence', 'niveau_etude', 'region', 'smoker', 'nationalité_francaise', 'revenu_estime_mois', 'montant_pret']
2025-06-08T07:07:33.366866+0000 INFO Starting training iteration 0 of 3 (from_existing_model=False)
2025-06-08T07:07:33.388117+0000 INFO No previous model_id, creating new model.
2025-06-08T07:07:40.352846+0000 INFO Model performances: {'MSE': 146266288.0, 'MAE': 11943.537109375, 'R²': 0.666932225227356}
2025-06-08T07:07:46.142722+0000 INFO Run 1 terminé, run_id=9ff972d81d1f40898fa9e4c1f26f6a9b
2025-06-08T07:07:46.160619+0000 INFO Starting training iteration 1 of 3 (from_existing_model=False)
2025-06-08T07:07:46.178586+0000 INFO Loading model from previous model_id: 9ff972d81d1f40898fa9e4c1f26f6a9b
2025-06-08T07:07:54.114708+0000 INFO Model performances: {'MSE': 805235.9375, 'MAE': 793.504150390625, 'R²': 0.9981663823127747}
2025-06-08T07:08:00.305635+0000 INFO Run 2 terminé, run_id=5508df8b28f140e8b6ce86035df4148c
2025-06-08T07:08:00.320568+0000 INFO Starting training iteration 2 of 3 (from_existing_model=False)
2025-06-08T07:08:00.337884+0000 INFO Loading model from previous model_id: 5508df8b28f140e8b6ce86035df4148c
2025-06-08T07:08:08.067684+0000 INFO Model performances: {'MSE': 85412.78125, 'MAE': 254.39431762695312, 'R²': 0.9998055100440979}
2025-06-08T07:08:14.663926+0000 INFO Run 3 terminé, run_id=10a7b3c05afa44f8992a1e69aff59eb2
2025-06-08T07:08:14.679573+0000 INFO Nouveau modèle de prédiction mis à jour avec run_id: 10a7b3c05afa44f8992a1e69aff59eb2 (sauvegardé dans models/current_model.json)
2025-06-08T07:14:56.189544+0000 INFO Route '/predict' called with data: [30, 170.0, 70.0, 2500.0, 'F', 'Oui', 'Aucun', 'Auvergne-Rhône-Alpes', 'Oui', 'Oui']
2025-06-08T07:14:56.315106+0000 INFO Model loaded from MLflow run ID: 10a7b3c05afa44f8992a1e69aff59eb2
2025-06-08T07:14:56.398832+0000 INFO Prediction made: [46463.16], prediction value: 46463.16015625
2025-06-08T07:15:00.376746+0000 INFO Route '/predict' called with data: [30, 170.0, 70.0, 2500.0, 'M', 'Oui', 'Aucun', 'Auvergne-Rhône-Alpes', 'Oui', 'Oui']
2025-06-08T07:15:00.449834+0000 INFO Model loaded from MLflow run ID: 10a7b3c05afa44f8992a1e69aff59eb2
2025-06-08T07:15:00.541808+0000 INFO Prediction made: [18479.904], prediction value: 18479.904296875
2025-06-08T07:42:17.818632+0000 INFO Route '/retrain' called for retraining with data_path=data/df_new.csv, from_existing_model=False
2025-06-08T07:42:17.829415+0000 INFO Données chargées pour réentraînement: shape=(2000, 13), colonnes=['nom', 'prenom', 'age', 'taille', 'poids', 'sexe', 'sport_licence', 'niveau_etude', 'region', 'smoker', 'nationalité_francaise', 'revenu_estime_mois', 'montant_pret']
2025-06-08T07:42:17.829813+0000 INFO Starting training iteration 0 of 3 (from_existing_model=False)
2025-06-08T07:42:17.880399+0000 INFO No previous model_id, creating new model.
2025-06-08T07:42:26.075025+0000 INFO Model performances: {'MSE': 18382725.01025585, 'MAE': 3066.298711844458, 'R²': 0.8301862027094716}
2025-06-08T07:42:35.261960+0000 INFO Run 1 terminé, run_id=b9a2f330458a47c097a049520b089b79
2025-06-08T07:42:35.281857+0000 INFO Starting training iteration 1 of 3 (from_existing_model=False)
2025-06-08T07:42:35.306237+0000 INFO Loading model from previous model_id: b9a2f330458a47c097a049520b089b79
2025-06-08T07:42:42.114958+0000 INFO Model performances: {'MSE': 13492112.390705328, 'MAE': 2320.5130409942385, 'R²': 0.875364134683078}
2025-06-08T07:42:48.157424+0000 INFO Run 2 terminé, run_id=b9a44b9b70a743739df4efb3127f31b5
2025-06-08T07:42:48.173599+0000 INFO Starting training iteration 2 of 3 (from_existing_model=False)
2025-06-08T07:42:48.190983+0000 INFO Loading model from previous model_id: b9a44b9b70a743739df4efb3127f31b5
2025-06-08T07:42:56.489808+0000 INFO Model performances: {'MSE': 13451429.478846755, 'MAE': 2278.4720555161316, 'R²': 0.8757399505506214}
2025-06-08T07:43:04.318686+0000 INFO Run 3 terminé, run_id=b7881843aa8049729d314d77ff057338
2025-06-08T07:43:04.339538+0000 INFO Nouveau modèle de prédiction mis à jour avec run_id: b7881843aa8049729d314d77ff057338 (sauvegardé dans models/current_model.json)
2025-06-08T07:43:39.211652+0000 INFO Route '/predict' called with data: [10, 142.0, 224.0, 18100.0, 'M', 'Non', 'Aucun', 'Auvergne-Rhône-Alpes', 'Oui', 'Oui']
2025-06-08T07:43:39.297618+0000 INFO Model loaded from MLflow run ID: b7881843aa8049729d314d77ff057338
2025-06-08T07:43:39.388651+0000 INFO Prediction made: [66503.375], prediction value: 66503.375
2025-06-08T07:44:19.350338+0000 INFO Route '/predict' called with data: [48, 174.0, 82.0, 2700.0, 'M', 'Oui', 'Aucun', 'Bretagne', 'Non', 'Oui']
2025-06-08T07:44:19.426791+0000 INFO Model loaded from MLflow run ID: b7881843aa8049729d314d77ff057338
2025-06-08T07:44:19.510266+0000 INFO Prediction made: [5732.161], prediction value: 5732.1611328125
